trims:
  # Ticks (20 ticks = 1 second). Example: 6000 ticks = 5 minutes
  world-options:
    s-o:
      min: 5
      max: 10

    o-e:
      min: 5
      max: 10

    duration:
      meltdown: 27000

    generation:
      cpt: 2
      buffer-chunks: 1
      start-intial-generation-ticks: 60
      start-after-empty-ticks: 60
      max-generated-worlds: 5

  structure-options:
    0:
      name: Desert Temple
      min: 500
      max: 1000
      follow-distance: 60
      follow-penalty-multiplier: 0.5
      world-border: true
      wd-buffer: 10
      time-to-meltdown: 27000
      chance: 10
    1:
      name: Jungle Temple
      min: 10
      max: 20
      follow-distance: 60
      follow-penalty-multiplier: 0.5
      world-border: true
      wd-buffer: 10
      time-to-meltdown: 27000
      chance: 10
    2:
      name: Ancient City
      min: 10
      max: 20
      follow-distance: 60
      follow-penalty-multiplier: 0.5
      world-border: true
      wd-buffer: 10
      time-to-meltdown: 27000
      chance: 10
    3:
      name: Trial Chamber
      min: 10
      max: 20
      follow-distance: 60
      follow-penalty-multiplier: 0.5
      world-border: true
      wd-buffer: 10
      time-to-meltdown: 27000
      chance: 10
    4:
      name: Trail Ruins
      min: 10
      max: 20
      follow-distance: 60
      follow-penalty-multiplier: 0.5
      world-border: true
      wd-buffer: 10
      time-to-meltdown: 27000
      chance: 10
    5:
      name: Stronghold
      min: 10
      max: 20
      follow-distance: 60
      follow-penalty-multiplier: 0.5
      world-border: true
      wd-buffer: 10
      time-to-meltdown: 27000
      chance: 10
    6:
      name: Mansion
      min: 10
      max: 20
      follow-distance: 60
      follow-penalty-multiplier: 0.5
      world-border: true
      wd-buffer: 10
      time-to-meltdown: 27000
      chance: 10
    7:
      name: Monument
      min: 10
      max: 20
      follow-distance: 60
      follow-penalty-multiplier: 0.5
      world-border: true
      wd-buffer: 10
      time-to-meltdown: 27000
      chance: 10
    8:
      name: Pillager Outpost
      min: 10
      max: 20
      follow-distance: 60
      follow-penalty-multiplier: 0.5
      world-border: true
      wd-buffer: 10
      time-to-meltdown: 27000
      chance: 10
    9:
      name: Shipwreck
      min: 10
      max: 20
      follow-distance: 60
      follow-penalty-multiplier: 0.5
      world-border: true
      wd-buffer: 10
      time-to-meltdown: 27000
      chance: 10

  player-options:
    # Ticks | 24hrs currently
    rift-cooldown: 1728000
    spawn-variation: 10
    per-material-structure-selection: true

  teleport-handler:
    # In seconds
    timings:
      1: 50
      2: 35
      3: 20
      4: 10

  haste-handler:
    distance: 10