trims:
  # Ticks (20 ticks = 1 second). Example: 6000 ticks = 5 minutes
  world-options:
    s-o:
      min: 5
      max: 10

    o-e:
      min: 5
      max: 10

    spawn-variation:
      min: 5
      max: 10

    duration:
      meltdown: 27000

    generation:
      cpt: 2
      buffer-chunks: 1

  player-options:
    # Ticks | 24hrs currently
    rift-cooldown: 1728000

  teleport-handler:
    # In seconds
    timings:
      1: 50
      2: 35
      3: 20
      4: 10

  haste-handler:
    distance: 10