trims:
  world-options:
    s-o:
      min: 5
      max: 10

    o-e:
      min: 5
      max: 10

  teleport-handler:
    # In seconds
    timings:
      1: 50
      2: 35
      3: 20
      4:

  haste-handler:
    distance: 10