trims:
  world-options:
    s-o:
      min: 5
      max: 10

    o-e:
      min: 5
      max: 10

    spawn-variation:
      min: 5
      max: 10

    duration:
      # Ticks (20 ticks = 1 second). Example: 6000 ticks = 5 minutes
      meltdown: 9000

  teleport-handler:
    # In seconds
    timings:
      1: 50
      2: 35
      3: 20
      4:

  haste-handler:
    distance: 10